# Generated by Django 2.2.1 on 2019-07-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('c_name', models.CharField(default='', max_length=250)),
                ('designition', models.CharField(default='', max_length=250)),
                ('hospital_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
                ('password2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Taken_email', to='main_app.User')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Taken_username', to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Consultant')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_email', to='main_app.User')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_username+', to='main_app.User')),
            ],
        ),
    ]
