# Generated by Django 2.2.1 on 2019-07-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
