# Generated by Django 2.2.1 on 2019-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190728_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=250),
        ),
    ]
